In [213]:
# !pip install pandas
# !pip install odfpy
import pandas as pd
import numpy as np
import matplotlib
from numpy import linalg as LA

matplotlib.use('TkAgg')
import matplotlib.pyplot as plt

def Fitting(x, y, polinom_size):
        vandermond_tr = np.zeros((polinom_size,x.size))
        
        for i in range(polinom_size):
              vandermond_tr[i] = x**i
        
        vandermond = vandermond_tr.transpose()
        
        XX = vandermond_tr.dot(vandermond)
        XX_inv = np.linalg.inv(XX)
        XY = vandermond_tr.dot(y)
        coeff_vector = XX_inv.dot(XY)

        return coeff_vector
    
def GaussMethod(x, y, Xo, Func_value, polinom_size):
    vandermond_tr = np.zeros((polinom_size,x.size))
   
    xo = Xo
    yo = Func_value
    lagrange_vec = np.zeros((polinom_size,1))
    condition1 = np.zeros(polinom_size+1)
        
    for i in range(polinom_size):
        vandermond_tr[i] = x**i
        lagrange_vec[i] = -0.5 * xo**i
        condition1[i] = xo**i
    
    vandermond = vandermond_tr.transpose()
    condition1 = condition1.transpose()
        
    XX = vandermond_tr.dot(vandermond)
    XY = vandermond_tr.dot(y)
    XY = np.append(XY, yo)
#     print(XY)
    print(condition1)


#     A_new = np.concatenate((XX, lagrange_vec.T), axis=1)
    A = np.hstack((XX,lagrange_vec))
    A = np.vstack((A, condition1))
    print(lagrange_vec)
    print("------")
    print(A)
    

    coeff_vector = LA.solve(A, XY)
    return coeff_vector

###################################################
pd.set_option("display.max.columns", None)
df1 = pd.read_excel("sample.xlsx", sheet_name='list1')

discrete_size= 1000
step = 1./discrete_size

#######
# print(df1)
arr1 = df1.to_numpy()
in1=arr1[:,0]
out1=arr1[:,1]

x=in1[::-1]
y = out1[::-1]
######################################
mg=0.00001
ln_y = np.log(y)
ln_x = np.log(1-x**mg)

begin = 0
end = 1
coeff_matrix = GaussMethod(ln_x,ln_y, ln_x[0], ln_y[0], 3)
# coeff_matrix = Fitting(ln_x,ln_y, 2)
temp = np.linspace(np.min(ln_x), np.max(ln_x), discrete_size)
Y = coeff_matrix[0] + coeff_matrix[1] * temp

# coeff_matrix =np.zeros((number,4))
# splines = np.zeros((number, discrete_size ))
# first_derivative = np.zeros((number, discrete_size))
# second_derivative = np.zeros((number,
# discrete_size))

    

[ 1.         -9.61204028 92.3913183   0.        ]
[[ -0.5       ]
 [  4.80602014]
 [-46.19565915]]
------
[[ 5.40000000e+01 -7.42424199e+02  1.06966688e+04 -5.00000000e-01]
 [-7.42424199e+02  1.06966688e+04 -1.61601776e+05  4.80602014e+00]
 [ 1.06966688e+04 -1.61601776e+05  2.55841774e+06 -4.61956591e+01]
 [ 1.00000000e+00 -9.61204028e+00  9.23913183e+01  0.00000000e+00]]


In [222]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])
y = np.array([1, 3, 7, 11, 15, 20, 25, 35, 46, 84, 100, 120, 132, 140, 147, 146, 144, 135, 125, 109, 101, 92, 85, 78, 69])
polinom_size = 8
# coeff_matrix = Fitting(x,y, polinom_size)
coeff_matrix = GaussMethod(x,y, 15, 150, polinom_size)
temp = np.linspace(np.min(x), np.max(x), discrete_size)
Y = np.zeros((temp.size))

for i in range(polinom_size):
    Y += coeff_matrix[i] * temp**i
        

################################################

plt.plot(x, y, 'bo')
plt.plot(temp, Y, linewidth=2)


plt.grid(True)
plt.show()


[1.00000000e+00 1.50000000e+01 2.25000000e+02 3.37500000e+03
 5.06250000e+04 7.59375000e+05 1.13906250e+07 1.70859375e+08
 0.00000000e+00]
[[-5.00000000e-01]
 [-7.50000000e+00]
 [-1.12500000e+02]
 [-1.68750000e+03]
 [-2.53125000e+04]
 [-3.79687500e+05]
 [-5.69531250e+06]
 [-8.54296875e+07]]
------
[[ 2.50000000e+01  3.41000000e+02  6.10100000e+03  1.22201000e+05
   2.60062100e+06  5.75170010e+07  1.30679710e+09  3.02893558e+10
  -5.00000000e-01]
 [ 3.41000000e+02  6.10100000e+03  1.22201000e+05  2.60062100e+06
   5.75170010e+07  1.30679710e+09  3.02893558e+10  7.12940718e+11
  -7.50000000e+00]
 [ 6.10100000e+03  1.22201000e+05  2.60062100e+06  5.75170010e+07
   1.30679710e+09  3.02893558e+10  7.12940718e+11  1.69868657e+13
  -1.12500000e+02]
 [ 1.22201000e+05  2.60062100e+06  5.75170010e+07  1.30679710e+09
   3.02893558e+10  7.12940718e+11  1.69868657e+13  4.08757795e+14
  -1.68750000e+03]
 [ 2.60062100e+06  5.75170010e+07  1.30679710e+09  3.02893558e+10
   7.12940718e+11  1.69868657e+

In [214]:
b = 1./coeff_matrix[1]
a = -np.exp(-coeff_matrix[0] / coeff_matrix[1])
print(a)
print(b)
S = np.linspace(np.min(x), np.max(x), discrete_size)
p = ((1 - S**mg)/(-a))**(1./b)

-1.1739276913796222e-06
0.5163964813778372


In [216]:
################################################

# plt.plot(x, y, 'bo')
# plt.plot(S, p, linewidth=2)
plt.plot(ln_x, ln_y, 'bo')
plt.plot(temp, Y, linewidth=2)


plt.grid(True)
plt.show()